Plugins: Ooyala: Fix a fatal error when class definition is included multiple times
require() vs require_once()

Fatal error: require(): Cannot redeclare class ooyalaapi in /home/wpcom/public_html/wp-content/themes/vip/plugins/ooyala/api_proxy.php on line 2 

http://keepingtheirblogsgoing.wordpress.com/2013/06/14/14-jun-2013-220048-utc-fatal-error/


git-svn-id: https://vip-svn.wordpress.com/plugins@109703 dd790b09-5c1c-0410-8744-875116bcd8a6